#scrubHTML.py
#Produces a hash table to convert strange HTML tags and unicode symbols to
#something more readable.  This can be maintained manually or build automoatically
#from Pat 's spreadsheet hashBash1.xls)
def makeHashTable():
    myTable = []
    newEntry = ('&#038;', '&')
    myTable.append(newEntry)
    newEntry = ('&nbsp;', ' ')
    myTable.append(newEntry)
    newEntry = ('&#160;', ' ')
    myTable.append(newEntry)
    newEntry = ('&#xA0;', ' ')
    myTable.append(newEntry)
    newEntry = ('&iexcl;', ' ')
    myTable.append(newEntry)
    newEntry = ('&#161;', ' ')
    myTable.append(newEntry)
    newEntry = ('&#xA1;', ' ')
    myTable.append(newEntry)
    newEntry = ('&cent;', '(cents)')
    myTable.append(newEntry)
    newEntry = ('&#162;', '(cents)')
    myTable.append(newEntry)
    newEntry = ('&#xA2;', '(cents)')
    myTable.append(newEntry)
    newEntry = ('&pound;', '(pounds)')
    myTable.append(newEntry)
    newEntry = ('&#163;', '(pounds)')
    myTable.append(newEntry)
    newEntry = ('&#xA3;', '(pounds)')
    myTable.append(newEntry)
    newEntry = ('&curren;', '')
    myTable.append(newEntry)
    newEntry = ('&#164;', '')
    myTable.append(newEntry)
    newEntry = ('&#xA4;', '')
    myTable.append(newEntry)
    newEntry = ('&yen;', '(yen)')
    myTable.append(newEntry)
    newEntry = ('&#165;', '(yen)')
    myTable.append(newEntry)
    newEntry = ('&#xA5;', '(yen)')
    myTable.append(newEntry)
    newEntry = ('&brvbar;', '')
    myTable.append(newEntry)
    newEntry = ('&#166;', '')
    myTable.append(newEntry)
    newEntry = ('&#xA6;', '')
    myTable.append(newEntry)
    newEntry = ('&mdash;', '-')
    myTable.append(newEntry)
    newEntry = ('&sect;', '(section)')
    myTable.append(newEntry)
    newEntry = ('&#167;', '(section)')
    myTable.append(newEntry)
    newEntry = ('&#xA7;', '(section)')
    myTable.append(newEntry)
    newEntry = ('&uml;', '')
    myTable.append(newEntry)
    newEntry = ('&#168;', '')
    myTable.append(newEntry)
    newEntry = ('&#xA8;', '')
    myTable.append(newEntry)
    newEntry = ('&copy;', '(c)')
    myTable.append(newEntry)
    newEntry = ('&#169;', '(c)')
    myTable.append(newEntry)
    newEntry = ('&#xA9;', '(c)')
    myTable.append(newEntry)
    newEntry = ('&ordf;', 'th')
    myTable.append(newEntry)
    newEntry = ('&#170;', 'th')
    myTable.append(newEntry)
    newEntry = ('&#xAA;', 'th')
    myTable.append(newEntry)
    newEntry = ('&laquo;', '`')
    myTable.append(newEntry)
    newEntry = ('&#171;', '`')
    myTable.append(newEntry)
    newEntry = ('&#xAB;', '`')
    myTable.append(newEntry)
    newEntry = ('&not;', '(not)')
    myTable.append(newEntry)
    newEntry = ('&#172;', '(not)')
    myTable.append(newEntry)
    newEntry = ('&#xAC;', '(not)')
    myTable.append(newEntry)
    newEntry = ('&shy;', '-')
    myTable.append(newEntry)
    newEntry = ('&#173;', '-')
    myTable.append(newEntry)
    newEntry = ('&#xAD;', '-')
    myTable.append(newEntry)
    newEntry = ('&reg;', '(r)')
    myTable.append(newEntry)
    newEntry = ('&#174;', '(r)')
    myTable.append(newEntry)
    newEntry = ('&#xAE;', '(r)')
    myTable.append(newEntry)
    newEntry = ('&macr;', '')
    myTable.append(newEntry)
    newEntry = ('&#175;', '')
    myTable.append(newEntry)
    newEntry = ('&#xAF;', '')
    myTable.append(newEntry)
    newEntry = ('&deg;', '(degrees)')
    myTable.append(newEntry)
    newEntry = ('&#176;', '(degrees)')
    myTable.append(newEntry)
    newEntry = ('&#xB0;', '(degrees)')
    myTable.append(newEntry)
    newEntry = ('&plusmn;', '(plus or minus)')
    myTable.append(newEntry)
    newEntry = ('&#177;', '(plus or minus)')
    myTable.append(newEntry)
    newEntry = ('&#xB1;', '(plus or minus)')
    myTable.append(newEntry)
    newEntry = ('&sup2;', '^2')
    myTable.append(newEntry)
    newEntry = ('&#178;', '^2')
    myTable.append(newEntry)
    newEntry = ('&#xB2;', '^2')
    myTable.append(newEntry)
    newEntry = ('&sup3;', '^3')
    myTable.append(newEntry)
    newEntry = ('&#179;', '^3')
    myTable.append(newEntry)
    newEntry = ('&#xB3;', '^3')
    myTable.append(newEntry)
    newEntry = ('&acute;', '`')
    myTable.append(newEntry)
    newEntry = ('&#180;', '`')
    myTable.append(newEntry)
    newEntry = ('&#xB4;', '`')
    myTable.append(newEntry)
    newEntry = ('&micro;', 'mu')
    myTable.append(newEntry)
    newEntry = ('&#181;', 'mu')
    myTable.append(newEntry)
    newEntry = ('&#xB5;', 'mu')
    myTable.append(newEntry)
    newEntry = ('&para;', '')
    myTable.append(newEntry)
    newEntry = ('&#182;', '')
    myTable.append(newEntry)
    newEntry = ('&#xB6;', '')
    myTable.append(newEntry)
    newEntry = ('&middot;', '')
    myTable.append(newEntry)
    newEntry = ('&#183;', '')
    myTable.append(newEntry)
    newEntry = ('&#xB7;', '')
    myTable.append(newEntry)
    newEntry = ('&cedil;', '')
    myTable.append(newEntry)
    newEntry = ('&#184;', '')
    myTable.append(newEntry)
    newEntry = ('&#xB8;', '')
    myTable.append(newEntry)
    newEntry = ('&sup1;', '')
    myTable.append(newEntry)
    newEntry = ('&#185;', '')
    myTable.append(newEntry)
    newEntry = ('&#xB9;', '')
    myTable.append(newEntry)
    newEntry = ('&ordm;', 'th')
    myTable.append(newEntry)
    newEntry = ('&#186;', 'th')
    myTable.append(newEntry)
    newEntry = ('&#xBA;', 'th')
    myTable.append(newEntry)
    newEntry = ('&raquo;', '')
    myTable.append(newEntry)
    newEntry = ('&#187;', '')
    myTable.append(newEntry)
    newEntry = ('&#xBB;', '')
    myTable.append(newEntry)
    newEntry = ('&frac14;', '\1/4')
    myTable.append(newEntry)
    newEntry = ('&#188;', '\1/4')
    myTable.append(newEntry)
    newEntry = ('&#xBC;', '\1/4')
    myTable.append(newEntry)
    newEntry = ('&frac12;', '\1/2')
    myTable.append(newEntry)
    newEntry = ('&#189;', '\1/2')
    myTable.append(newEntry)
    newEntry = ('&#xBD;', '\1/2')
    myTable.append(newEntry)
    newEntry = ('&frac34;', '\3/4')
    myTable.append(newEntry)
    newEntry = ('&#190;', '\3/4')
    myTable.append(newEntry)
    newEntry = ('&#xBE;', '\3/4')
    myTable.append(newEntry)
    newEntry = ('&iquest;', '')
    myTable.append(newEntry)
    newEntry = ('&#191;', '')
    myTable.append(newEntry)
    newEntry = ('&#xBF;', '')
    myTable.append(newEntry)
    newEntry = ('&Agrave;', 'A')
    myTable.append(newEntry)
    newEntry = ('&#192;', 'A')
    myTable.append(newEntry)
    newEntry = ('&#xC0;', 'A')
    myTable.append(newEntry)
    newEntry = ('&Aacute;', 'A')
    myTable.append(newEntry)
    newEntry = ('&#193;', 'A')
    myTable.append(newEntry)
    newEntry = ('&#xC1;', 'A')
    myTable.append(newEntry)
    newEntry = ('&Acirc;', 'A')
    myTable.append(newEntry)
    newEntry = ('&#194;', 'A')
    myTable.append(newEntry)
    newEntry = ('&#xC2;', 'A')
    myTable.append(newEntry)
    newEntry = ('&Atilde;', 'A')
    myTable.append(newEntry)
    newEntry = ('&#195;', 'A')
    myTable.append(newEntry)
    newEntry = ('&#xC3;', 'A')
    myTable.append(newEntry)
    newEntry = ('&Auml;', 'A')
    myTable.append(newEntry)
    newEntry = ('&#196;', 'A')
    myTable.append(newEntry)
    newEntry = ('&#xC4;', 'A')
    myTable.append(newEntry)
    newEntry = ('&Aring;', 'A')
    myTable.append(newEntry)
    newEntry = ('&#197;', 'A')
    myTable.append(newEntry)
    newEntry = ('&#xC5;', 'A')
    myTable.append(newEntry)
    newEntry = ('&AElig;', 'AE')
    myTable.append(newEntry)
    newEntry = ('&#198;', 'AE')
    myTable.append(newEntry)
    newEntry = ('&#xC6;', 'AE')
    myTable.append(newEntry)
    newEntry = ('&Ccedil;', 'C')
    myTable.append(newEntry)
    newEntry = ('&#199;', 'C')
    myTable.append(newEntry)
    newEntry = ('&#xC7;', 'C')
    myTable.append(newEntry)
    newEntry = ('&Egrave;', 'E')
    myTable.append(newEntry)
    newEntry = ('&#200;', 'E')
    myTable.append(newEntry)
    newEntry = ('&#xC8;', 'E')
    myTable.append(newEntry)
    newEntry = ('&Eacute;', 'E')
    myTable.append(newEntry)
    newEntry = ('&#201;', 'E')
    myTable.append(newEntry)
    newEntry = ('&#xC9;', 'E')
    myTable.append(newEntry)
    newEntry = ('&Ecirc;', 'E')
    myTable.append(newEntry)
    newEntry = ('&#202;', 'E')
    myTable.append(newEntry)
    newEntry = ('&#xCA;', 'E')
    myTable.append(newEntry)
    newEntry = ('&Euml;', 'E')
    myTable.append(newEntry)
    newEntry = ('&#203;', 'E')
    myTable.append(newEntry)
    newEntry = ('&#xCB;', 'E')
    myTable.append(newEntry)
    newEntry = ('&Igrave;', 'I')
    myTable.append(newEntry)
    newEntry = ('&#204;', 'I')
    myTable.append(newEntry)
    newEntry = ('&#xCC;', 'I')
    myTable.append(newEntry)
    newEntry = ('&Iacute;', 'I')
    myTable.append(newEntry)
    newEntry = ('&#205;', 'I')
    myTable.append(newEntry)
    newEntry = ('&#xCD;', 'I')
    myTable.append(newEntry)
    newEntry = ('&Icirc;', 'I')
    myTable.append(newEntry)
    newEntry = ('&#206;', 'I')
    myTable.append(newEntry)
    newEntry = ('&#xCE;', 'I')
    myTable.append(newEntry)
    newEntry = ('&Iuml;', 'I')
    myTable.append(newEntry)
    newEntry = ('&#207;', 'I')
    myTable.append(newEntry)
    newEntry = ('&#xCF;', 'I')
    myTable.append(newEntry)
    newEntry = ('&ETH;', '')
    myTable.append(newEntry)
    newEntry = ('&#208;', '')
    myTable.append(newEntry)
    newEntry = ('&#xD0;', '')
    myTable.append(newEntry)
    newEntry = ('&Ntilde;', 'N')
    myTable.append(newEntry)
    newEntry = ('&#209;', 'N')
    myTable.append(newEntry)
    newEntry = ('&#xD1;', 'N')
    myTable.append(newEntry)
    newEntry = ('&Ograve;', 'O')
    myTable.append(newEntry)
    newEntry = ('&#210;', 'O')
    myTable.append(newEntry)
    newEntry = ('&#xD2;', 'O')
    myTable.append(newEntry)
    newEntry = ('&Oacute;', 'O')
    myTable.append(newEntry)
    newEntry = ('&#211;', 'O')
    myTable.append(newEntry)
    newEntry = ('&#xD3;', 'O')
    myTable.append(newEntry)
    newEntry = ('&Ocirc;', 'O')
    myTable.append(newEntry)
    newEntry = ('&#212;', 'O')
    myTable.append(newEntry)
    newEntry = ('&#xD4;', 'O')
    myTable.append(newEntry)
    newEntry = ('&Otilde;', 'O')
    myTable.append(newEntry)
    newEntry = ('&#213;', 'O')
    myTable.append(newEntry)
    newEntry = ('&#xD5;', 'O')
    myTable.append(newEntry)
    newEntry = ('&Ouml;', 'O')
    myTable.append(newEntry)
    newEntry = ('&#214;', 'O')
    myTable.append(newEntry)
    newEntry = ('&#xD6;', 'O')
    myTable.append(newEntry)
    newEntry = ('&times;', '*')
    myTable.append(newEntry)
    newEntry = ('&#215;', '*')
    myTable.append(newEntry)
    newEntry = ('&#xD7;', '*')
    myTable.append(newEntry)
    newEntry = ('&Oslash;', 'O')
    myTable.append(newEntry)
    newEntry = ('&#216;', 'O')
    myTable.append(newEntry)
    newEntry = ('&#xD8;', 'O')
    myTable.append(newEntry)
    newEntry = ('&Ugrave;', 'U')
    myTable.append(newEntry)
    newEntry = ('&#217;', 'U')
    myTable.append(newEntry)
    newEntry = ('&#xD9;', 'U')
    myTable.append(newEntry)
    newEntry = ('&Uacute;', 'U')
    myTable.append(newEntry)
    newEntry = ('&#218;', 'U')
    myTable.append(newEntry)
    newEntry = ('&#xDA;', 'U')
    myTable.append(newEntry)
    newEntry = ('&Ucirc;', 'U')
    myTable.append(newEntry)
    newEntry = ('&#219;', 'U')
    myTable.append(newEntry)
    newEntry = ('&#xDB;', 'U')
    myTable.append(newEntry)
    newEntry = ('&Uuml;', 'U')
    myTable.append(newEntry)
    newEntry = ('&#220;', 'U')
    myTable.append(newEntry)
    newEntry = ('&#xDC;', 'U')
    myTable.append(newEntry)
    newEntry = ('&Yacute;', 'Y')
    myTable.append(newEntry)
    newEntry = ('&#221;', 'Y')
    myTable.append(newEntry)
    newEntry = ('&#xDD;', 'Y')
    myTable.append(newEntry)
    newEntry = ('&THORN;', '')
    myTable.append(newEntry)
    newEntry = ('&#222;', '')
    myTable.append(newEntry)
    newEntry = ('&#xDE;', '')
    myTable.append(newEntry)
    newEntry = ('&szlig;', '')
    myTable.append(newEntry)
    newEntry = ('&#223;', '')
    myTable.append(newEntry)
    newEntry = ('&#xDF;', '')
    myTable.append(newEntry)
    newEntry = ('&agrave;', 'a')
    myTable.append(newEntry)
    newEntry = ('&#224;', 'a')
    myTable.append(newEntry)
    newEntry = ('&#xE0;', 'a')
    myTable.append(newEntry)
    newEntry = ('&aacute;', 'a')
    myTable.append(newEntry)
    newEntry = ('&#225;', 'a')
    myTable.append(newEntry)
    newEntry = ('&#xE1;', 'a')
    myTable.append(newEntry)
    newEntry = ('&acirc;', 'a')
    myTable.append(newEntry)
    newEntry = ('&#226;', 'a')
    myTable.append(newEntry)
    newEntry = ('&#xE2;', 'a')
    myTable.append(newEntry)
    newEntry = ('&atilde;', 'a')
    myTable.append(newEntry)
    newEntry = ('&#227;', 'a')
    myTable.append(newEntry)
    newEntry = ('&#xE3;', 'a')
    myTable.append(newEntry)
    newEntry = ('&auml;', 'a')
    myTable.append(newEntry)
    newEntry = ('&#228;', 'a')
    myTable.append(newEntry)
    newEntry = ('&#xE4;', 'a')
    myTable.append(newEntry)
    newEntry = ('&aring;', 'a')
    myTable.append(newEntry)
    newEntry = ('&#229;', 'a')
    myTable.append(newEntry)
    newEntry = ('&#xE5;', 'a')
    myTable.append(newEntry)
    newEntry = ('&aelig;', 'ae')
    myTable.append(newEntry)
    newEntry = ('&#230;', 'ae')
    myTable.append(newEntry)
    newEntry = ('&#xE6;', 'ae')
    myTable.append(newEntry)
    newEntry = ('&ccedil;', 'c')
    myTable.append(newEntry)
    newEntry = ('&#231;', 'c')
    myTable.append(newEntry)
    newEntry = ('&#xE7;', 'c')
    myTable.append(newEntry)
    newEntry = ('&egrave;', 'e')
    myTable.append(newEntry)
    newEntry = ('&#232;', 'e')
    myTable.append(newEntry)
    newEntry = ('&#xE8;', 'e')
    myTable.append(newEntry)
    newEntry = ('&eacute;', 'e')
    myTable.append(newEntry)
    newEntry = ('&#233;', 'e')
    myTable.append(newEntry)
    newEntry = ('&#xE9;', 'e')
    myTable.append(newEntry)
    newEntry = ('&ecirc;', 'e')
    myTable.append(newEntry)
    newEntry = ('&#234;', 'e')
    myTable.append(newEntry)
    newEntry = ('&#xEA;', 'e')
    myTable.append(newEntry)
    newEntry = ('&euml;', 'e')
    myTable.append(newEntry)
    newEntry = ('&#235;', 'e')
    myTable.append(newEntry)
    newEntry = ('&#xEB;', 'e')
    myTable.append(newEntry)
    newEntry = ('&igrave;', 'i')
    myTable.append(newEntry)
    newEntry = ('&#236;', 'i')
    myTable.append(newEntry)
    newEntry = ('&#xEC;', 'i')
    myTable.append(newEntry)
    newEntry = ('&iacute;', 'i')
    myTable.append(newEntry)
    newEntry = ('&#237;', 'i')
    myTable.append(newEntry)
    newEntry = ('&#xED;', 'i')
    myTable.append(newEntry)
    newEntry = ('&icirc;', 'i')
    myTable.append(newEntry)
    newEntry = ('&#238;', 'i')
    myTable.append(newEntry)
    newEntry = ('&#xEE;', 'i')
    myTable.append(newEntry)
    newEntry = ('&iuml;', 'i')
    myTable.append(newEntry)
    newEntry = ('&#239;', 'i')
    myTable.append(newEntry)
    newEntry = ('&#xEF;', 'i')
    myTable.append(newEntry)
    newEntry = ('&eth;', '')
    myTable.append(newEntry)
    newEntry = ('&#240;', '')
    myTable.append(newEntry)
    newEntry = ('&#xF0;', '')
    myTable.append(newEntry)
    newEntry = ('&ntilde;', 'n')
    myTable.append(newEntry)
    newEntry = ('&#241;', 'n')
    myTable.append(newEntry)
    newEntry = ('&#xF1;', 'n')
    myTable.append(newEntry)
    newEntry = ('&ograve;', 'o')
    myTable.append(newEntry)
    newEntry = ('&#242;', 'o')
    myTable.append(newEntry)
    newEntry = ('&#xF2;', 'o')
    myTable.append(newEntry)
    newEntry = ('&oacute;', 'o')
    myTable.append(newEntry)
    newEntry = ('&#243;', 'o')
    myTable.append(newEntry)
    newEntry = ('&#xF3;', 'o')
    myTable.append(newEntry)
    newEntry = ('&ocirc;', 'o')
    myTable.append(newEntry)
    newEntry = ('&#244;', 'o')
    myTable.append(newEntry)
    newEntry = ('&#xF4;', 'o')
    myTable.append(newEntry)
    newEntry = ('&otilde;', 'o')
    myTable.append(newEntry)
    newEntry = ('&#245;', 'o')
    myTable.append(newEntry)
    newEntry = ('&#xF5;', 'o')
    myTable.append(newEntry)
    newEntry = ('&ouml;', 'o')
    myTable.append(newEntry)
    newEntry = ('&#246;', 'o')
    myTable.append(newEntry)
    newEntry = ('&#xF6;', 'o')
    myTable.append(newEntry)
    newEntry = ('&divide;', '/')
    myTable.append(newEntry)
    newEntry = ('&#247;', '/')
    myTable.append(newEntry)
    newEntry = ('&#xF7;', '/')
    myTable.append(newEntry)
    newEntry = ('&oslash;', 'o')
    myTable.append(newEntry)
    newEntry = ('&#248;', 'o')
    myTable.append(newEntry)
    newEntry = ('&#xF8;', 'o')
    myTable.append(newEntry)
    newEntry = ('&ugrave;', 'u')
    myTable.append(newEntry)
    newEntry = ('&#249;', 'u')
    myTable.append(newEntry)
    newEntry = ('&#xF9;', 'u')
    myTable.append(newEntry)
    newEntry = ('&uacute;', 'u')
    myTable.append(newEntry)
    newEntry = ('&#250;', 'u')
    myTable.append(newEntry)
    newEntry = ('&#xFA;', 'u')
    myTable.append(newEntry)
    newEntry = ('&ucirc;', 'u')
    myTable.append(newEntry)
    newEntry = ('&#251;', 'u')
    myTable.append(newEntry)
    newEntry = ('&#xFB;', 'u')
    myTable.append(newEntry)
    newEntry = ('&uuml;', 'u')
    myTable.append(newEntry)
    newEntry = ('&#252;', 'u')
    myTable.append(newEntry)
    newEntry = ('&#xFC;', 'u')
    myTable.append(newEntry)
    newEntry = ('&yacute;', 'y')
    myTable.append(newEntry)
    newEntry = ('&#253;', 'y')
    myTable.append(newEntry)
    newEntry = ('&#xFD;', 'y')
    myTable.append(newEntry)
    newEntry = ('&thorn;', '')
    myTable.append(newEntry)
    newEntry = ('&#254;', '')
    myTable.append(newEntry)
    newEntry = ('&#xFE;', '')
    myTable.append(newEntry)
    newEntry = ('&yuml;', 'y')
    myTable.append(newEntry)
    newEntry = ('&#255;', 'y')
    myTable.append(newEntry)
    newEntry = ('&#xFF;', 'y')
    myTable.append(newEntry)
    newEntry = ('&#8218;', '\'')
    myTable.append(newEntry)
    newEntry = ('&#402;', 'f')
    myTable.append(newEntry)
    newEntry = ('&#8222;', '\"')
    myTable.append(newEntry)
    newEntry = ('&#8230;', '.')
    myTable.append(newEntry)
    newEntry = ('&#8224;', '')
    myTable.append(newEntry)
    newEntry = ('&#8225;', '')
    myTable.append(newEntry)
    newEntry = ('&#710;', '')
    myTable.append(newEntry)
    newEntry = ('&#8240;', '%')
    myTable.append(newEntry)
    newEntry = ('&#352;', 'S')
    myTable.append(newEntry)
    newEntry = ('&#8249;', '`')
    myTable.append(newEntry)
    newEntry = ('&#338;', '')
    myTable.append(newEntry)
    newEntry = ('&#8216;', '`')
    myTable.append(newEntry)
    newEntry = ('&#8217;', '`')
    myTable.append(newEntry)
    newEntry = ('&#8220;', '`')
    myTable.append(newEntry)
    newEntry = ('&#8221;', '`')
    myTable.append(newEntry)
    newEntry = ('&#8226;', '-')
    myTable.append(newEntry)
    newEntry = ('&#8211;', '-')
    myTable.append(newEntry)
    newEntry = ('&#8212;', '-')
    myTable.append(newEntry)
    newEntry = ('&#732;', '`')
    myTable.append(newEntry)
    newEntry = ('&#8482;', '(TM)')
    myTable.append(newEntry)
    newEntry = ('&#353', 's')
    myTable.append(newEntry)
    newEntry = ('&#8250', '`')
    myTable.append(newEntry)
    newEntry = ('&#339', '')
    myTable.append(newEntry)
    newEntry = ('&#376', 'Y')
    myTable.append(newEntry)
    newEntry = ('\xc3\xa2\xe2\x82\xac\xc5\x93', '`')
    myTable.append(newEntry)
    newEntry = ('\xc3\xa2\xe2\x82\xac\xc2\x9d', '`')
    myTable.append(newEntry)
    newEntry = ('\xc3\xa2\xe2\x82\xac\xe2\x80\x9c', '..')
    myTable.append(newEntry)
    newEntry = ('20%', ' ')
    myTable.append(newEntry)
    newEntry = ('23%', '#')
    myTable.append(newEntry)
    newEntry = ('24%', '$')
    myTable.append(newEntry)
    newEntry = ('25%', '%')
    myTable.append(newEntry)
    newEntry = ('26%', '&')
    myTable.append(newEntry)
    newEntry = ('%2F', '/')
    myTable.append(newEntry)
    newEntry = ('%3A', ':')
    myTable.append(newEntry)
    newEntry = ('%3B', ';')
    myTable.append(newEntry)
    newEntry = ('%3C', '<')
    myTable.append(newEntry)
    newEntry = ('%3D', '=')
    myTable.append(newEntry)
    newEntry = ('%3E', '>')
    myTable.append(newEntry)
    newEntry = ('%3F', '?')
    myTable.append(newEntry)
    newEntry = ('40%', '@')
    myTable.append(newEntry)
    newEntry = ('%5B', '[')
    myTable.append(newEntry)
    newEntry = ('%5C', '\\')
    myTable.append(newEntry)
    newEntry = ('%5D', ']')
    myTable.append(newEntry)
    newEntry = ('%5E', '^')
    myTable.append(newEntry)
    newEntry = ('60%', '`')
    myTable.append(newEntry)
    newEntry = ('%7B', '{')
    myTable.append(newEntry)
    newEntry = ('%7C', '|')
    myTable.append(newEntry)
    newEntry = ('%7D', '}')
    myTable.append(newEntry)
    newEntry = ('%7E', '~')
    myTable.append(newEntry)
    return myTable
